# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [7]:
import numpy as np
i=j=k=0
array=np.zeros((i,j,k))
print(array)

squarmeter_of_house = list(range(10))
rooms_of_house=list(range(10))
price_of_house=list(range(10))

array = np.array([squarmeter_of_house, rooms_of_house, price_of_house])
print(array)

[]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


2. Transpose the array you have created, so that every line can represent features of one house.

In [11]:
array_new = array.transpose()

print(array_new)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]


3. Display the shape of the array and explain what it means.

In [13]:
print("Shape of array : ", array_new.shape)

Shape of array :  (10, 3)


4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [22]:


array_6x5 = np.array([[[1,1,1,1,1],
                      [1,0,1,0,1],
                      [1,1,1,1,1],
                      [1,0,1,0,1],
                      [1,1,1,1,1],
                      [1,0,1,0,1]]
])

print("shape(6 x 5) -->")
print(array_6x5)


count_zeros=array_6x5.count(0)
print

shape(6 x 5) -->
[[[1 1 1 1 1]
  [1 0 1 0 1]
  [1 1 1 1 1]
  [1 0 1 0 1]
  [1 1 1 1 1]
  [1 0 1 0 1]]]
