# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [6]:
import numpy as np
data=np.load('data.npy')

2. Display the mean and the standard deviation for each column.

In [10]:
for i in range(len(data[0])): #returns first column numbers
    print("Mean for each column   :", np.mean(data[:,i]))
    print("Standart deviation for each column :", np.std(data[:,i]))


Mean for each column   : 0.05
Standart deviation for each column : 0.21794494717703364
Mean for each column   : 35.64994
Standart deviation for each column : 8.074558574770514
Mean for each column   : 31.442185000000002
Standart deviation for each column : 9.133896757971101
Mean for each column   : 18.958999999999996
Standart deviation for each column : 18.779266732223597
Mean for each column   : 4.224999999999999
Standart deviation for each column : 0.8080068069020212


3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [24]:
print("Substracting   :",'\n', np.subtract(data[:],[1,25,25,10,4]))
#print("Shape of array : ", data.shape)

Substracting   : 
 [[ 0.00000e+00 -2.40000e+01 -2.40000e+01 -9.00000e+00 -3.00000e+00]
 [-1.00000e+00  1.26878e+01  1.24016e+01  2.70000e-01  4.00000e-01]
 [-1.00000e+00  1.22003e+01  5.43760e+00  6.80700e+01  0.00000e+00]
 [-1.00000e+00  1.06846e+01  1.72660e+00  3.27700e+01  5.00000e-01]
 [-1.00000e+00  1.14171e+01  3.69910e+00  4.86000e+00  1.00000e-01]
 [-1.00000e+00  1.10535e+01  6.21350e+00  2.66800e+01  1.20000e+00]
 [-1.00000e+00  1.21958e+01  5.62410e+00  4.03300e+01  8.00000e-01]
 [-1.00000e+00  1.19653e+01  2.76330e+00 -3.07000e+00  3.00000e-01]
 [-1.00000e+00  1.38930e+01  1.44830e+00  1.62000e+00  2.00000e-01]
 [-1.00000e+00  1.23773e+01  1.13855e+01  5.30000e-01  8.00000e-01]
 [-1.00000e+00  1.08861e+01  1.06950e+00  1.84900e+01  9.00000e-01]
 [-1.00000e+00  1.24635e+01  1.13113e+01  5.29000e+00  3.00000e-01]
 [-1.00000e+00  1.20201e+01  1.10845e+01  0.00000e+00  1.00000e-01]
 [-1.00000e+00  1.26546e+01  1.66980e+00 -5.50000e+00  5.00000e-01]
 [-1.00000e+00  1.25318e+01  

4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [25]:
data=data*2
print(data)

[[  2.       2.       2.       2.       2.    ]
 [  0.      75.3756  74.8032  20.54     8.8   ]
 [  0.      74.4006  60.8752 156.14     8.    ]
 [  0.      71.3692  53.4532  85.54     9.    ]
 [  0.      72.8342  57.3982  29.72     8.2   ]
 [  0.      72.107   62.427   73.36    10.4   ]
 [  0.      74.3916  61.2482 100.66     9.6   ]
 [  0.      73.9306  55.5266  13.86     8.6   ]
 [  0.      77.786   52.8966  23.24     8.4   ]
 [  0.      74.7546  72.771   21.06     9.6   ]
 [  0.      71.7722  52.139   56.98     9.8   ]
 [  0.      74.927   72.6226  30.58     8.6   ]
 [  0.      74.0402  72.169   20.       8.2   ]
 [  0.      75.3092  53.3396   9.       9.    ]
 [  0.      75.0636  59.696   35.16     9.2   ]
 [  0.      78.0776  88.3066  15.04     9.    ]
 [  0.      76.714   89.7372  20.1      8.2   ]
 [  0.      71.4036  56.299   12.5      8.2   ]
 [  0.      75.3766  74.7936  21.26     8.2   ]
 [  0.      84.3642  85.1856  11.62     8.    ]]
